version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=yourpassword
      - DB_NAME=webcrawler

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"  # React dev usually runs on 3000, nginx serves on 80

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: webcrawler
    volumes:
      - mysql_data:/var/lib/mysql

